
project_id = "brgycopmuuanrrqmrdmf"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600

[functions.create-subscription]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.coinbase-onramp]
verify_jwt = true

[functions.mindfulnest-ai-chat]
verify_jwt = true

[functions.privy-supabase-link]
verify_jwt = true

[secrets]
PAYSTACK_PUBLIC_KEY = "pk_test_9ecd61b54dae039b80266f1fb7aa4bd1f"
