// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-mood-entries.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthorized() {
  return {
    isError: true,
    content: [{ type: "text", text: "Not authenticated" }]
  };
}
function errorResult(message) {
  return {
    isError: true,
    content: [{ type: "text", text: message }]
  };
}
function jsonResult(value) {
  return {
    content: [{ type: "text", text: JSON.stringify(value) }],
    structuredContent: { value }
  };
}

// src/lib/mcp/tools/list-mood-entries.ts
var list_mood_entries_default = defineTool({
  name: "list_mood_entries",
  title: "List mood entries",
  description: "List the signed-in user's recent mood entries, most recent first. Each entry has id, mood, intensity (1-10), note, date, and activities.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("How many entries to return (max 100)."),
    since: z.string().optional().describe("Optional ISO date (YYYY-MM-DD). Only return entries on or after this date.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, since }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    let q = supabaseForUser(ctx).from("mood_entries").select("id, mood, intensity, note, date, activities, created_at").order("date", { ascending: false }).limit(limit);
    if (since) q = q.gte("date", since);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult({ entries: data ?? [] });
  }
});

// src/lib/mcp/tools/get-mood-entry.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.23.8";
var get_mood_entry_default = defineTool2({
  name: "get_mood_entry",
  title: "Get mood entry",
  description: "Fetch a single mood entry owned by the signed-in user by id.",
  inputSchema: {
    id: z2.string().uuid().describe("Mood entry UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const { data, error } = await supabaseForUser(ctx).from("mood_entries").select("id, mood, intensity, note, date, activities, created_at").eq("id", id).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Mood entry not found");
    return jsonResult({ entry: data });
  }
});

// src/lib/mcp/tools/create-mood-entry.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.23.8";
var create_mood_entry_default = defineTool3({
  name: "create_mood_entry",
  title: "Log mood entry",
  description: "Log a new mood entry for the signed-in user. `mood` is a short label (e.g. 'happy', 'anxious', 'calm'), `intensity` is 1-10, `note` is optional free text, `date` defaults to today.",
  inputSchema: {
    mood: z3.string().trim().min(1).max(64).describe("Mood label (e.g. happy, anxious, calm)."),
    intensity: z3.number().int().min(1).max(10).describe("Intensity from 1 (weak) to 10 (strong)."),
    note: z3.string().max(2e3).optional().describe("Optional note about how the user feels."),
    date: z3.string().optional().describe("ISO date (YYYY-MM-DD). Defaults to today."),
    activities: z3.array(z3.string()).optional().describe("Optional list of activities associated with the entry.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ mood, intensity, note, date, activities }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("mood_entries").insert({
      user_id: ctx.getUserId(),
      mood,
      intensity,
      note: note ?? null,
      date: date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      activities: activities ?? null
    }).select("id, mood, intensity, note, date, activities, created_at").single();
    if (error) return errorResult(error.message);
    await sb.rpc("increment_mood_entries_count");
    return jsonResult({ entry: data });
  }
});

// src/lib/mcp/tools/delete-mood-entry.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.23.8";
var delete_mood_entry_default = defineTool4({
  name: "delete_mood_entry",
  title: "Delete mood entry",
  description: "Permanently delete one of the signed-in user's mood entries by id.",
  inputSchema: {
    id: z4.string().uuid().describe("Mood entry UUID to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const { error } = await supabaseForUser(ctx).from("mood_entries").delete().eq("id", id);
    if (error) return errorResult(error.message);
    return jsonResult({ deleted: id });
  }
});

// src/lib/mcp/tools/list-focus-sessions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^3.23.8";
var list_focus_sessions_default = defineTool5({
  name: "list_focus_sessions",
  title: "List focus sessions",
  description: "List the signed-in user's completed focus sessions, most recent first.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).default(20).describe("How many sessions to return (max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const { data, error } = await supabaseForUser(ctx).from("focus_sessions").select("id, name, duration, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) return errorResult(error.message);
    return jsonResult({ sessions: data ?? [] });
  }
});

// src/lib/mcp/tools/create-focus-session.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z6 } from "npm:zod@^3.23.8";
var create_focus_session_default = defineTool6({
  name: "create_focus_session",
  title: "Log focus session",
  description: "Log a completed focus session for the signed-in user. `duration` is in minutes. Also updates streak and totals.",
  inputSchema: {
    name: z6.string().trim().min(1).max(128).describe("Session label, e.g. 'Deep work', 'Study'."),
    duration: z6.number().int().min(1).max(600).describe("Session length in minutes (max 600).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, duration }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("focus_sessions").insert({ user_id: ctx.getUserId(), name, duration }).select("id, name, duration, created_at").single();
    if (error) return errorResult(error.message);
    await sb.rpc("update_user_stats_on_session_complete", { session_duration: duration });
    return jsonResult({ session: data });
  }
});

// src/lib/mcp/tools/get-focus-stats.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_focus_stats_default = defineTool7({
  name: "get_focus_stats",
  title: "Get focus stats",
  description: "Return the signed-in user's focus totals: total sessions, total focus minutes, current streak, and today's session count.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const { data, error } = await supabaseForUser(ctx).rpc("get_user_focus_stats");
    if (error) return errorResult(error.message);
    return jsonResult({ stats: data });
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_profile_default = defineTool8({
  name: "get_profile",
  title: "Get profile & subscription",
  description: "Return the signed-in user's profile summary: email (from token), subscription plan/status, wellness stats (total sessions, focus minutes, current streak, mood entries), task streaks, and total dopamine rewards.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const sb = supabaseForUser(ctx);
    const uid = ctx.getUserId();
    const [subRes, statsRes, streaksRes, rewardsRes] = await Promise.all([
      sb.rpc("get_user_subscription"),
      sb.from("user_stats").select("*").eq("user_id", uid).maybeSingle(),
      sb.from("user_task_streaks").select("task_type, current_streak, total_completions, last_completed_date").eq("user_id", uid),
      sb.from("dopamine_rewards").select("amount").eq("user_id", uid)
    ]);
    if (subRes.error) return errorResult(subRes.error.message);
    if (statsRes.error) return errorResult(statsRes.error.message);
    if (streaksRes.error) return errorResult(streaksRes.error.message);
    if (rewardsRes.error) return errorResult(rewardsRes.error.message);
    const totalRewards = (rewardsRes.data ?? []).reduce((sum, r) => sum + (r.amount ?? 0), 0);
    return jsonResult({
      user: {
        id: uid,
        email: ctx.getUserEmail() ?? null
      },
      subscription: subRes.data?.[0] ?? null,
      stats: statsRes.data ?? null,
      task_streaks: streaksRes.data ?? [],
      total_rewards: totalRewards
    });
  }
});

// src/lib/mcp/tools/list-wallet.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.1";
var list_wallet_default = defineTool9({
  name: "list_wallet",
  title: "List wallet addresses",
  description: "List the signed-in user's linked wallet addresses (Base network). Read-only \u2014 send, receive, and buy operations are not exposed over MCP; they stay in the Mindfulnest app.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const { data, error } = await supabaseForUser(ctx).from("user_wallets").select("id, wallet_address, wallet_provider, created_at").eq("user_id", ctx.getUserId());
    if (error) return errorResult(error.message);
    return jsonResult({ wallets: data ?? [] });
  }
});

// src/lib/mcp/tools/search-therapists.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z7 } from "npm:zod@^3.23.8";
var search_therapists_default = defineTool10({
  name: "search_therapists",
  title: "Search therapist directory",
  description: "Search Mindfulnest's approved therapist directory. Optional filters: specialty (matches any of the therapist's specialties), language (substring match), location (substring match). Requires a Pro or Elite subscription, matching the app's therapist gate.",
  inputSchema: {
    specialty: z7.string().optional().describe("Specialty to match, e.g. 'anxiety', 'trauma'."),
    language: z7.string().optional().describe("Language substring, e.g. 'English', 'Spanish'."),
    location: z7.string().optional().describe("Location substring, e.g. 'California', 'Lagos'."),
    limit: z7.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ specialty, language, location, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const sb = supabaseForUser(ctx);
    const { data: sub } = await sb.rpc("get_user_subscription");
    const planId = (sub?.[0]?.plan_id ?? "").toLowerCase();
    if (!planId.includes("pro") && !planId.includes("elite")) {
      return errorResult("Searching therapists requires a Pro or Elite subscription.");
    }
    let q = sb.from("therapist_applications").select(
      "id, full_name, title, credentials, bio, specialties, languages, location, price_range, session_types, years_of_experience"
    ).eq("status", "approved").limit(limit);
    if (specialty) q = q.contains("specialties", [specialty]);
    if (language) q = q.ilike("languages", `%${language}%`);
    if (location) q = q.ilike("location", `%${location}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult({ therapists: data ?? [] });
  }
});

// src/lib/mcp/tools/get-therapist.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z8 } from "npm:zod@^3.23.8";
var get_therapist_default = defineTool11({
  name: "get_therapist",
  title: "Get therapist details",
  description: "Fetch full public details for an approved therapist by id. Requires a Pro or Elite subscription.",
  inputSchema: {
    id: z8.string().uuid().describe("Therapist application UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const sb = supabaseForUser(ctx);
    const { data: sub } = await sb.rpc("get_user_subscription");
    const planId = (sub?.[0]?.plan_id ?? "").toLowerCase();
    if (!planId.includes("pro") && !planId.includes("elite")) {
      return errorResult("Viewing therapist details requires a Pro or Elite subscription.");
    }
    const { data, error } = await sb.from("therapist_applications").select(
      "id, full_name, title, credentials, bio, specialties, languages, location, price_range, session_types, years_of_experience, linkedin_url"
    ).eq("id", id).eq("status", "approved").maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Therapist not found or not approved.");
    return jsonResult({ therapist: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "brgycopmuuanrrqmrdmf";
var mcp_default = defineMcp({
  name: "mindfulnest-mcp",
  title: "Mindfulnest",
  version: "0.1.0",
  instructions: "Tools for Mindfulnest \u2014 a mental wellness app. Read and log the signed-in user's mood entries and focus sessions, view their profile, streaks, and wallet, and search the therapist directory.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_mood_entries_default,
    get_mood_entry_default,
    create_mood_entry_default,
    delete_mood_entry_default,
    list_focus_sessions_default,
    create_focus_session_default,
    get_focus_stats_default,
    get_profile_default,
    list_wallet_default,
    search_therapists_default,
    get_therapist_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
