// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brgycopmuuanrrqmrdmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZ3ljb3BtdXVhbnJycW1yZG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODIwNTYsImV4cCI6MjA2NTU1ODA1Nn0.Fnr19vqVXo9bOi1pVOOFDitK8pxaNuZb1KwomX2patU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);